= Behavioural Modification Leading to Peace and Happiness

The way one interacts in term of behaviour and speech in inevitably leads to reciprocity of ones action. Though this sounds very intuitive and simple, only a very few give the proper attention to this aspect of life. Maybe its simplicity makes people over look it. Being good to oneself is inextricably being good to others and being benevolent to others is being good to oneself. So developing restrain and sense of moral code to avoid socially detrimental behaviour, one can avoid situations of stress. This includes initial planing, execution of the action and remorse, regret and fear of repercussions that follow.  This is the sociological implications of behaviour, of which some specific cases will be discussed below, followed by the mental and psychological aspects.

Behavioural aspet

Every one values life and ones well being. Say someone attacks or hostile towards another then the other being may fight back. Also friends and relatives of the who was hurt or killed may avenge the action. Also others beings will in return become hostile towards the perpendicular person. If you take family feuds, gang revelries and even the enforcement of justice the same follows. It is either one avenging the action of another or fevering the week and enforcing restrain and punitive action on the aggressor. To be at peace and harmony one should respect life and well being of the others.

In every society people own private property which they tend to conserve and protect. If someone does not respect the notion of ownership and takes what is not given either by stealth, by force, by fraud, or by deceit, then repercussions follow. E.g. say you have a watch which is expensive and something you like very much, which subsequently gets stolen. It is needless to say you would be upset. If you find out who took it generally you would seek punitive action. The person doing it will have to exercise caution in steeling which is on its own stressful and also be in fear of getting caught afterwards. Though many think they can get away with sealing the majority do get caught. 

Another social aspect of life is relationships and marriage. When in a relationship people possessive of each other and develop the need of exclusivity in the relationship.

Also ones psychological well being is linked to ones behavioural actions. The metal states that motivate certain behaviours, also effect our mental well being and happiness. The effect can be felt at multiple stages: the initial motivations arises, when one follows through and in the future as a loop back effect of mental imprints initial negativity.

Sometimes there may be pressure to do detrimental actions for hardship or lack of other opportunities. A person out of work may steel to make ends meet. Though this gives a small edge in the long term this creates more problems.

In order to further ones own peace and happiness one has to practice some constraint. The above actions creates misery for oneself and others; refraining from unethical or immoral actions one can avoid such misery and also feel good about one self.
