= Basics of Being Peaceful and Harmonious to get Peace and Happiness

The way one interacts in term of behaviour and speech in inevitably leads to reciprocity of ones action. Though this sounds very intuitive and simple, only a very few give the proper attention to this aspect of life. Maybe its simplicity makes people over look it. Being good to oneself is inextricably being good to others and being benevolent to others is being good to oneself. This is the sociological aspect of ones behaviour.

Every one values life and ones well being. Say someone attacks or hostile towards another then the other being may fight back. Also friends and relatives of the who was hurt or killed may avenge the action. Also others beings will in return become hostile towards the perpendicular person. If you take family feuds, gang revelries and even the enforcement of justice the same follows. It is either one avenging the action of another or fevering the week and enforcing restrain and punitive action on the aggressor. To be at peace and harmony one should respect life and well being of the others.

In every society people own private property.

Also ones psychological well being is linked to ones behavioural actions. The metal states that motivate certain behaviours, also effect our mental well being and happiness. The effect can be felt at multiple stages: the initial motivations arises, when one follows through and in the future as a loop back effect of mental imprints 

In order to further ones own peace and happiness one has to practice some constraint.
